// 🛑 NOTICE: __generated__ folders should be added to .gitignore
// 🛑 In this repo I keep generated files only for demo purposes!
import * as Types from '../../../__generated__/types';

import { DocumentNode } from 'graphql';
export type OrderListItem = { __typename: 'Order', _id: any, orderID?: number | null | undefined, orderDate?: any | null | undefined, customerID?: string | null | undefined, employeeID?: number | null | undefined, freight?: number | null | undefined, employee?: { __typename: 'Employee', firstName?: string | null | undefined, lastName?: string | null | undefined, birthDate?: any | null | undefined, address?: { __typename: 'CustomerAddress', street?: string | null | undefined } | null | undefined } | null | undefined, customer?: { __typename: 'Customer', companyName?: string | null | undefined, address?: { __typename: 'CustomerAddress', city?: string | null | undefined } | null | undefined } | null | undefined };

export type Customer_data = { __typename: 'Customer', companyName?: string | null | undefined, address?: { __typename: 'CustomerAddress', city?: string | null | undefined } | null | undefined };

export const Customer_data = {"kind":"Document","definitions":[{"kind":"FragmentDefinition","name":{"kind":"Name","value":"Customer_data"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"Customer"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"companyName"}},{"kind":"Field","name":{"kind":"Name","value":"address"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"city"}}]}}]}}]} as unknown as DocumentNode;
export const OrderListItem = {"kind":"Document","definitions":[{"kind":"FragmentDefinition","name":{"kind":"Name","value":"OrderListItem"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"Order"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"_id"}},{"kind":"Field","name":{"kind":"Name","value":"orderID"}},{"kind":"Field","name":{"kind":"Name","value":"orderDate"}},{"kind":"Field","name":{"kind":"Name","value":"customerID"}},{"kind":"Field","name":{"kind":"Name","value":"employeeID"}},{"kind":"Field","name":{"kind":"Name","value":"employee"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"firstName"}},{"kind":"Field","name":{"kind":"Name","value":"lastName"}},{"kind":"Field","name":{"kind":"Name","value":"birthDate"}},{"kind":"Field","name":{"kind":"Name","value":"address"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"street"}}]}}]}},{"kind":"Field","name":{"kind":"Name","value":"customer"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"Customer_data"}}]}},{"kind":"Field","name":{"kind":"Name","value":"freight"}}]}},...Customer_data.definitions]} as unknown as DocumentNode;